version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: recipe-db
    environment:
      POSTGRES_DB: recipedb
      POSTGRES_USER: recipeuser
      POSTGRES_PASSWORD: recipepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipeuser -d recipedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: recipe-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipedb
      SPRING_DATASOURCE_USERNAME: recipeuser
      SPRING_DATASOURCE_PASSWORD: recipepass
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: